### ISSUE TITLE
MatrixMN breaks when using new version of Synapse or installing it the first time respectively

### ISSUE THREAD

**Issue by jhamfler** [reTHINK-project/dev-msg-node-matrix#14]
The new Synapse version is breaking when no `id` is provided in the appservice configuration.
I updated the config according to this [spec](https://github.com/matrix-org/matrix-doc/blob/master/specification/application_service_api.rst).
Commit: 31014286fc864d3cec1fac64c06afe1a21e31dd2

Synapse doesn't break anymore but it seems that the communication through the appservice in dev-msg-node-matrix isn't working anymore. I haven't found a solution yet. The appservice bridge module doesn't seem to have an id setter function implemented. [here](http://matrix-org.github.io/matrix-appservice-bridge/0.3.3/Cli.html#~generateRegistration)

**Comment by sdruesedow** [comment]
Tested with latest synapse v0.14
- can confirm that the id-field is now mandatory in the AS registration
- after adding the id-field it works for me again

**Comment by jhamfler** [comment]
Tested on the main and a second system. its working fine. No further changes required.
